[package]
name = "lunar_lander_rl"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.17.1"
ndarray-rand = "0.16.0"
rand = "0.9.2"
uom="0.37.0"
lazy_static="1.5.0"
macroquad="0.4.14"
strum = "0.26"
strum_macros = "0.26"
flamegraph = "0.6.10"
